version: "3.9"  # optional since v1.27.0
services:
  mysql:
    image: mariadb
    volumes:
      - ./_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=weather
      - MYSQL_USER=weather
      - MYSQL_PASSWORD=weather

