"""initial setup

Revision ID: 5e3b8b1552e4
Revises: 
Create Date: 2019-12-09 15:31:06.610731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e3b8b1552e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('temp', sa.Float(precision=2), nullable=True),
    sa.Column('pressure', sa.Float(precision=2), nullable=True),
    sa.Column('humidity', sa.Float(precision=2), nullable=True),
    sa.Column('gas', sa.Float(precision=2), nullable=True),
    sa.Column('battery', sa.Float(precision=2), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry')
    # ### end Alembic commands ###
