"""added mailer object

Revision ID: ce7183063afe
Revises: 5e3b8b1552e4
Create Date: 2020-10-01 11:42:49.216661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7183063afe'
down_revision = '5e3b8b1552e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_mail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sent_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_mail')
    # ### end Alembic commands ###
